id: IB2CF3FF5
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:21:52.269070+00:00
last_modified: 2022-12-14 18:21:52.269078+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-07-24T18:33:01.625Z'
  creationid: celso
  eft-text-id: UT22084-072-009
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_309-The_Sutra_on_Impermanence-v1
bases:
  AC42:
    source_metadata: null
    order: 1
    base_file: AC42.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
